### ISSUE TITLE
请问实现原理是什么？

### ISSUE THREAD

**Issue by Christopher-Songs** [RichardLuo0/WechatKiller#1]
通过某种方法屏蔽了微信本身的心跳包？还是只是简单粗暴的杀掉微信？

**Comment by RichardLuo0** [comment]
简单的杀掉微信。。。am kill com.tencent.mm命令不会影响fcm推送

**Comment by Christopher-Songs** [comment]
好吧，我现在就是用的这种方式，一直觉得这样有点暴力。。。感谢回复
